### ISSUE TITLE
how about fragment in mvp

### ISSUE THREAD

**Issue by nambv** [ivacf/archi#10]
- Does each Fragment have a matching presenter like Activity? I wanna use your mvp architecture to build app :) 
- Thanks in advanced @ivacf

**Comment by ivacf** [comment]
Yes, usually Fragments will have a matching Presenter in the same way as Activities.

**Comment by nambv** [comment]
Thanks a lot!
@ivacf if I set up views for Activity like TabLayout, ViewPager...should I do it in Activity or MvpView?

**Comment by ivacf** [comment]
The setup of views should happen in the Activity, the MvpView is just an java interface that your Activity implements so it won't have any setup code. 

I recommend you to use [Stackoverflow](http://stackoverflow.com/) for specific questions about your app architecture. This should be only for issues related to this project.
