### ISSUE TITLE
notifyDataSetChanged() and RepositoryAdapter.setRepositories()

### ISSUE THREAD

**Issue by leinardi** [ivacf/archi#20]
I just noticed that the call of notifyDataSetChanged() is not inside the setRepositories() method of RepositoryAdapter.

Is there a specific reason for this choice?

**Comment by ivacf** [comment]
No, I guess having it outside allows for more flexibility. For example, you may want to modify something in the list after calling `setRepositories()`  and before you notify that the dataset has changed.

**Comment by leinardi** [comment]
Ok, thanks for the info :+1:
