### ISSUE TITLE
Repository is not loaded, keyboard is not shown

### ISSUE THREAD

**Issue by johnjohndoe** [ivacf/archi#6]
I installed all three applications (_app_, _app-mvp_, _app-mvvm_) on an Android emulator. When I click into the input field to enter the GitHub user name **no keyboard** is shown. After entering the user name via the keyboard of my computer I press <kbd>Enter</kbd> but **nothing happens**.

![archi-mvvm](https://cloud.githubusercontent.com/assets/144518/10362428/e4bf7538-6dae-11e5-9e9e-e1480876d9a7.png)

**Comment by ivacf** [comment]
The loading triggers when you click the search button on the keyboard (EditText has `android:imeOptions="actionSearch"`)  
I'm not sure how this works on the emulator. Have you tried clicking the emulator's search button (top right corner) instead of Enter.

**Comment by johnjohndoe** [comment]
Nothing happens either when I press the emulator's search button.

**Comment by ivacf** [comment]
I think this may be a problem with the emulator not sending [IME_ACTION_SEARCH](http://developer.android.com/reference/android/view/inputmethod/EditorInfo.html#IME_ACTION_SEARCH) correctly. 
I think there is an option to get the software keyboard showing on the emulator, then clicking on the search button of the software keyboard should work.

**Comment by ThePromoter** [comment]
> I think there is an option to get the software keyboard showing on the emulator, then clicking on the search button of the software keyboard should work.

That's exactly what I did to get it working.

**Comment by ivacf** [comment]
I will look into changing the `imeOptions` to a different one that works well with the emulator.

**Comment by johnjohndoe** [comment]
The magnification glass is a good solution. Thank you.
Though, pressing <kbd>ENTER</kbd> still does **not** work.

**Comment by AndreiD** [comment]
+1 for glass not being an intuitive solution too
