### ISSUE TITLE
Activity/Fragment in Android MVVM with data binding

### ISSUE THREAD

**Issue by peacepassion** [ivacf/archi#7]
What is the role of Activity/Fragment in MVVM? In the `app-mvvm`, activity is located in the `activity` package. So the author treat them as part of View of MVVM.  
If activity/fragment treated as View, all the business code should be located in the VM? If so, the new VM just treat as original activity/fragment without any lifecycle calls because the VM consists of view operation and busyness operation.

**Comment by ivacf** [comment]
Activity and Fragments are usually treated as View. In theory, most of the logic should go in the VM so it's easier to unit test.  However, I think Activities and Fragment should still handle code that is strictly related to the Android framework and its lifecycle, for example if you are using the `GoogleApiClient`.
